#!/bin/sh

case "$1" in
    start)
        echo "Loading scull module"
        modprobe scull

        major=$(awk '$2=="scull" {print $1}' /proc/devices)

        rm -f /dev/scull[0-3] /dev/scull
        mknod /dev/scull0 c $major 0
        mknod /dev/scull1 c $major 1
        mknod /dev/scull2 c $major 2
        mknod /dev/scull3 c $major 3
        ln -sf scull0 /dev/scull
        chmod 664 /dev/scull[0-3]
        ;;

    stop)
        echo "Unloading scull module"
        rm -f /dev/scull /dev/scull[0-3]
        rmmod scull
        ;;

    restart)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0